controllers/OffersController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Travel;
use app\models\Request;
use app\models\Country;
use app\models\Type;
use app\models\Carriage;
use app\models\Currency;
use app\models\Airport;
use app\models\Weight;
use app\models\OffersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * RequestController implements the CRUD actions for Request model.
 */
class OffersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Request models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OffersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Request model.
     * @param integer $id
     * @return mixed
     */
    public function actionView()
    {
        if(Yii::$app->request->isAjax)
        {
            $post= Yii::$app->request->post();
            if($post){
              $offer=Travel::find()->with('user','from','to','carriage')->where(['id_travel'=>$post['id']])->one();
              //dd($offer->carriage->price);
              //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
              $digest="<div>";
              $digest.="<div class='row'><div  class='col-md-6'><label class='col-md-4' >From</label><p class='col-md-8'>".$offer->from->airport_tr."</p>";
              $digest.="<label  class='col-md-4' >Departure date</label><p  class='col-md-8' >".$offer->departure_date."</p>";
              $digest.="<label  class='col-md-4' >Departure time</label><p  class='col-md-8' >".$offer->departure_time."</p></div>";
              $digest.="<div class = 'col-md-6'><label  class='col-md-4' >To</label><p  class='col-md-8' >".$offer->to->airport_tr."</p>";
              $digest.="<label  class='col-md-4' >Arrival date</label><p  class='col-md-8' >".$offer->arrival_date."</p>";
              $digest.="<label  class='col-md-4' >Arrival time</label><p  class='col-md-8' >".$offer->arrival_time."</p></div></div><hr>";
              $digest.="<div class='row'><div class='col-md-6'><label class='col-md-4' >First name</label><p  class='col-md-8' >".$offer->user->first_name."</p>";
              $digest.="<label class='col-md-4' >Last name</label><p  class='col-md-8' >".$offer->user->last_name."</p>";
              $digest.="<label class='col-md-4' >Phone</label><p  class='col-md-8' >".$offer->user->phone."</p>";
              $digest.="<label class='col-md-4' >Email</label><p  class='col-md-8' >".$offer->user->email."</p>";
              $digest.="<label class='col-md-4' >Address</label><p  class='col-md-8' >".$offer->user->address."</p></div>";
              $digest.="<div class='col-md-6'><label class='col-md-4' >Type</label><p class='col-md-8' >".$offer->carriage->type->name_type."</p>";
              $digest.="<label class='col-md-4' >Weight</label><p class='col-md-8' >".$offer->carriage->weight->weight."</p>";
              $digest.="<label class='col-md-4' >Price</label><p class='col-md-8' >".$offer->carriage->price."</p>";
              $digest.="<label class='col-md-4' >Comment</label><p class='col-md-8' >".$offer->carriage->comment."</p></div></div>";
              $digest.="</div>";
              return $digest;
            }
        }

    }


    /**
     * Displays a single Request model.
     * @param integer $id
     * @return mixed
     */
    public function actionSearch()
    {
      $searchModel = new OffersSearch();
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
      //dd($dataProvider->getModels());
      return $this->render('index', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
      ]);
    }

    /**
     * Creates a new Request model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $post= Yii::$app->request->post();
        //dd($post);
        $model = new Travel();
        $carriage = new Carriage();

        $types = Type::find()->All();
        $weights = Weight::find()->All();
        $currencies = Currency::find()->All();
        $countries = Country::find()->All();
        $countryModel=new Country();

        $types= ArrayHelper::map($types,'id_type','name_tr_type');
        $countries= ArrayHelper::map($countries,'id_country','country_tr');
        $currencies= ArrayHelper::map($currencies,'id_currency','iso');
        $weights= ArrayHelper::map($weights,'id_weight','weight');

        if($post){
          if($carriage->load($post) && $carriage->save()){
            $model->id_user=Yii::$app->user->getId();
            $model->id_carriage=$carriage->id_carriage;
          }
          //dd($carriage->errors);

        }
        if ($model->load($post) && $model->save()) {
          return $this->redirect(['view', 'id' => $model->id_travel]);


        }/*elseif($model->errors){
          dd($model->errors);
        }*/
         else {
            return $this->render('create', [
                'model' => $model,
                'carriage'=>$carriage,
                'types'=>$types,
                'countryModel'=>$countryModel,
                'countries'=>$countries,
                'currencies'=>$currencies,
                'weights'=>$weights
            ]);
        }
    }

    /**
     * Updates an existing Request model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Request model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Request model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Request the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Travel::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAirports()
    {
      if(Yii::$app->request->isAjax)
      {
          $post=Yii::$app->request->post();
          $id=$post['id'];
          $airports= Airport::find()->where(['id_country'=>$id])->asArray()->all();
          //dd($airports);
          $list='<select>';
          foreach ($airports as $key => $value) {
            $list.='<option value="'.$value['id_airport'].'">'.$value['airport_tr'].'</option>';
          }
          $list.='</select>';
          return $list;
      }
    }
}

controllers/RequestsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Request;
use app\models\Country;
use app\models\Type;
use app\models\Carriage;
use app\models\Currency;
use app\models\Airport;
use app\models\Weight;
use app\models\RequestSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * RequestController implements the CRUD actions for Request model.
 */
class RequestsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Request models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RequestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Request model.
     * @param integer $id
     * @return mixed
     */
    public function actionView()
    {
        if(Yii::$app->request->isAjax)
        {
            $post= Yii::$app->request->post();
            if($post){
              $request=Request::find()->with('user','from','to','carriage')->where(['id'=>$post['id']])->one();
              //dd($request);
              //\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
              $digest="<div>";
              $digest.="<div class='row'><div  class='col-md-6'><label class='col-md-4' >From</label><p class='col-md-8' >".$request->from->airport_tr."</p>";
              $digest.="<label class='col-md-4' >To</label><p class='col-md-8' >".$request->to->airport_tr."</p>";
              $digest.="<label class='col-md-4' >Date</label><p class='col-md-8' >".$request->arrival_date."</p></div>";
              $digest.="<div class='col-md-6'><label class='col-md-4' >Type</label><p class='col-md-8' >".$request->carriage->type->name_type."</p>";
              $digest.="<label class='col-md-4' >Weight</label><p class='col-md-8' >".$request->carriage->weight->weight."</p>";
              $digest.="<label class='col-md-4' >Price</label><p class='col-md-8' >".$request->carriage->price.' '.$request->carriage->currency->iso."</p>";
              $digest.="<label class='col-md-4' >Comment</label><p class='col-md-8' >".$request->carriage->comment."</p></div></div><hr>";
              $digest.="<div class='row'><div class='col-md-6'><label class='col-md-4' >First name</label><p class='col-md-8' >".$request->user->first_name."</p>";
              $digest.="<label class='col-md-4' >Last name</label><p class='col-md-8' >".$request->user->last_name."</p>";
              $digest.="<label class='col-md-4' >Phone</label><p class='col-md-8' >".$request->user->phone."</p>";
              $digest.="</div><div class='col-md-6' ><label class='col-md-4' >Email</label><p class='col-md-8' >".$request->user->email."</p>";
              $digest.="<label class='col-md-4' >Address</label><p class='col-md-8' >".$request->user->address."</p></div></div>";
              $digest.="</div>";
              return $digest;
            }
        }

    }

    /**
     * Creates a new Request model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $post= Yii::$app->request->post();
        //dd($post);
        $model = new Request();
        $carriage = new Carriage();

        $types = Type::find()->All();
        $weights = Weight::find()->All();
        $currencies = Currency::find()->All();
        $countries = Country::find()->All();
        $countryModel=new Country();

        $types= ArrayHelper::map($types,'id_type','name_tr_type');
        $countries= ArrayHelper::map($countries,'id_country','country_tr');
        $currencies= ArrayHelper::map($currencies,'id_currency','iso');
        $weights= ArrayHelper::map($weights,'id_weight','weight');

        if($post){
          if($carriage->load($post) && $carriage->save()){
            $model->user_id=28;
            $model->carriage_id=$carriage->id_carriage;
          }
          //dd($carriage->errors);

        }
        if ($model->load($post) && $model->save()) {
          return $this->redirect(['view', 'id' => $model->id]);


        }elseif($model->errors){
          dd($model->errors);
        }
         else {
            return $this->render('create', [
                'model' => $model,
                'carriage'=>$carriage,
                'types'=>$types,
                'countryModel'=>$countryModel,
                'countries'=>$countries,
                'currencies'=>$currencies,
                'weights'=>$weights
            ]);
        }
    }

    /**
     * Updates an existing Request model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Request model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Request model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Request the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Request::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionAirports()
    {
      if(Yii::$app->request->isAjax)
      {
          $post=Yii::$app->request->post();
          $id=$post['id'];
          $airports= Airport::find()->where(['id_country'=>$id])->asArray()->all();
          //dd($airports);
          $list='<select>';
          foreach ($airports as $key => $value) {
            $list.='<option value="'.$value['id_airport'].'">'.$value['airport_tr'].'</option>';
          }
          $list.='</select>';
          return $list;
      }
    }
}

views/layouts/index.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Pjax;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url ;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<?php Pjax::begin(['id'=>'pjax-main','timeout'=>5000,'options'=>['style'=> 'height:100%']]); ?>
<?php //Pjax::begin(['timeout' => 5000 ]); ?>

<div class="wrap-index">


    <div id="index-content" class="container-fluid" style="height:100%" >
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>
<?php Pjax::end() ; ?>


<?php $this->endBody() ?>
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/URI.js/1.18.12/URI.min.js">
</script>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Pjax;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url ;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<?php Pjax::begin(['id'=>'pjax-main','timeout'=>5000,'options'=>['style'=> 'height:100%']]); ?>
<?php //Pjax::begin(['timeout' => 5000 ]); ?>


    <?php
    NavBar::begin([
        'brandLabel' => '<img class="col-md-10 img-responsive" src="/images/logo_200.png"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
            'style'=> (Url::current()=='/site/index' || Url::current()=='/')? "display:none":"",

        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Post', 'items'=>[
              ['label' => 'Offer', 'url' => ['/offers/create']],
              ['label' => 'Request', 'url' => ['/requests/create']],

            ]],
            ['label' => 'Search',   'items'=>[
              ['label' => 'Offer', 'url' => ['/offers/index']],
              ['label' => 'Request', 'url' => ['/requests/index']],

            ]],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->first_name . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
<div class="wrap">
    <div id="main-content" class="container-fluid col-md-10 col-md-offset-1"    <?php   if(Url::current()!='/site/index' && Url::current()!='/') echo 'style="display:none;height:200%;"'; else echo 'style="height:100%"'; ?> >
        <?php /* Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) */ ?>
        <?= $content ?>
    </div>
</div>
<?php Pjax::end() ; ?>

<!--<div class="container">
<footer class="footer">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
</footer>
</div>-->

<div id="loading-container" class="collapse">
</div>
<?php $this->endBody() ?>
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/URI.js/1.18.12/URI.min.js">
</script>
</html>
<?php $this->endPage() ?>